### ISSUE TITLE
error: Convert 'Serial' from 'Serial_' to 'HardwareSerial&'HardwareSerial &serialPort = Serial

### ISSUE THREAD

**Issue by kayali1411** [mvento/SIM900-lib#1]
Hi,
I have tired to use the library, but I get the following error when I compile the code
<img width="1260" alt="arduino1" src="https://user-images.githubusercontent.com/15734859/29742987-741e2ca0-8a91-11e7-9ab2-0e1569769c06.png">
<img width="1262" alt="arduino" src="https://user-images.githubusercontent.com/15734859/29742994-7fbbf68c-8a91-11e7-8333-89b06e73aab9.png">

I noticed, you mentioned that this error was solved, so I don't know if there is something wrong from my side.

Thanks in advance

**Comment by mvento** [comment]
Hi,
The example was outdated, you need to pass the Serial (or Serial1, Serial2, SerialX)  object in the constructor.
I solved the problem in the last commit.

best regards.
